### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [kr-g/pyjsoncfg#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pyjsoncfg -w /tmp/ext pyjsoncfg==0.0.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pyjsoncfg==0.0.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/0fd/4f6cab3c3b22d/pyjsoncfg-0.0.3.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-djzcilsl/pyjsoncfg/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-djzcilsl/pyjsoncfg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-djzcilsl/pyjsoncfg/pip-egg-info
         cwd: /tmp/pip-wheel-djzcilsl/pyjsoncfg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-djzcilsl/pyjsoncfg/setup.py", line 3, in <module>
        with open("README.MD", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.MD'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kr-g** [comment]
why do you want to build the package again ? 
(what is the use case here ?)
what restricts you from using "pip install" ?

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass --no-binary :all:, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311

**Comment by kr-g** [comment]
you want to build on trusted system, instead of pulling from from pypi where its unclear what comes with it.

**Comment by thatch** [comment]
Yes, either for trust or the ability to use new architectures (in the case of binary packages).

**Comment by kr-g** [comment]
this one has no binaries, since pure python. - anyway -
try.
https://test.pypi.org/project/pyjsoncfg/0.0.4a0/

**Comment by thatch** [comment]
That should work.

**Comment by kr-g** [comment]
should? or does? work ;)

**Comment by kr-g** [comment]
it's not yet on pypi it's test.pypi

**Comment by thatch** [comment]
Does work.

```
[tim@rygel ~]$ D=$(mktemp -d)
[tim@rygel ~]$ python3 -m venv $D
[tim@rygel ~]$ $D/bin/pip install --no-binary pyjsoncfg -i https://test.pypi.org/simple/ pyjsoncfg==0.0.4a0
Looking in indexes: https://test.pypi.org/simple/
Collecting pyjsoncfg==0.0.4a0
  Downloading https://test-files.pythonhosted.org/packages/5f/76/e2d2e460960693c67ef251afec7981f6499522cd754e2b1c9fbe2e3ab1d8/pyjsoncfg-0.0.4a0.tar.gz
Installing collected packages: pyjsoncfg
  Running setup.py install for pyjsoncfg ... done
Successfully installed pyjsoncfg-0.0.4a0
```

**Comment by kr-g** [comment]
its on pypi now. github updated.

**Comment by kr-g** [comment]
be the first (of all downloaders) to give a star
